#!/bin/bash
PREFIX=/usr/local

PARALLEL_MAKE=-j1
CONFIGURATION_OPTIONS="--disable-multilib --disable-nls"

BINUTILS_VERSION=binutils-2.28
LINUX_KERNEL_VERSION=linux-4.11.7
GCC_VERSION=gcc-7.1.0
GLIBC_VERSION=glibc-2.25
MPFR_VERSION=mpfr-3.1.5
GMP_VERSION=gmp-6.1.1
MPC_VERSION=mpc-1.0.3
ISL_VERSION=isl-0.16.1
CLOOG_VERSION=cloog-0.18.1

TERMCAP_VERSION=termcap-1.3.1
GDB_VERSION=gdb-8.0
